# Generated by Django 3.1.7 on 2021-03-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.DeleteModel(
            name='Rusults',
        ),
        migrations.DeleteModel(
            name='Tampers',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
